# Generated by Django 3.1 on 2021-06-23 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_auto_20210622_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='descripcion')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('image', models.ImageField(upload_to='photos/products', verbose_name='imagen')),
                ('stock', models.IntegerField(verbose_name='cantidad')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha-creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='fecha-modificacion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
