# Generated by Django 3.1 on 2021-06-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='apellido')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='usuario')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50, verbose_name='telefono')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha_registro')),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='personal')),
                ('is_active', models.BooleanField(default=False, verbose_name='activo')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='super_usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
